### ISSUE TITLE
Database question

### ISSUE THREAD

**Issue by ciumexan** [jedireza/frame#105]
Hello Jedi Reza!  

Quick question:
I am thinking on changing the db (from mongo to aerospike / cassandra / dynamo)
Is there any possibility to change this on-the-fly? I mean, maybe we want to migrate in the future

I am thinking on translating my app slim framework to node. 

Anne
wannabe api Jedi

**Comment by jedireza** [comment]
Thank for opening an issue.

Currently frame only supports MongoDB. This is primarily because we use the [`hapi-mongo-models`](https://github.com/jedireza/hapi-mongo-models) module.

You could use something like [Bookshelf](http://bookshelfjs.org/) or [Sequelize](http://docs.sequelizejs.com/en/latest/), but you'd have to go through Frame and update everything to work with those kinds of models instead.
