### ISSUE TITLE
Database Migration Question

### ISSUE THREAD

**Issue by entrptaher** [jedireza/frame#135]
Hi,
Is there any good way to transfer database data between drywall, aqua and frame? 
I have a test website with around 50 accounts. If I want to move it into frame, do I have no way to transfer them? 
If I create something with frame and want to transfer the data to aqua, I see absolutely no way.  
Do I have to create accounts manually? What about the passwords then?

Doing all of these because 
- there is no easy to understand version like drywall, 
- and frame is very basic.
- but I still need the data to see many things.

Sorry for such bad English.

**Comment by jedireza** [comment]
Thanks for open an issue.

> Is there any good way to transfer database data between drywall, aqua and frame? I have a test website with around 50 accounts. If I want to move it into frame, do I have no way to transfer them? 

To my knowledge there isn't anything built already to help migrate the user parts of the collections between Drywall and Frame (Aqua is Frame with a React front-end). The biggest difference between Drywall and Frame models is using `hapi-mongo-models` instead of `mongoose`. So depending on how heavily you use `mongoose` features, can/will make migrating more difficult.

> If I create something with frame and want to transfer the data to aqua, I see absolutely no way.

These are practically the same thing in regards to the data models. Any changes would be very minor.

> Do I have to create accounts manually? What about the passwords then?

I wouldn't move 50 accounts "manually", I'd definitely create a script to help so I could run it, fix it and try again. The passwords should be fine to just copy over, both systems use `bcrypt` to hash passwords.

> Sorry for such bad English.

I didn't notice. 😉 

Good luck. If you create something and you'd like to share, please update this thread.
