### ISSUE TITLE
 Error: "value" must be an object

### ISSUE THREAD

**Issue by Tavousi** [jedireza/frame#152]
Hi, there
i trying to use postman for check this api but evertime i get this :
```
{
  "statusCode": 400,
  "error": "Bad Request",
  "message": "\"value\" must be an object",
  "validation": {
    "source": "payload",
    "keys": [
      "value"
    ]
  }
}
```
![Image of Yaktocat](http://up.persianscript.ir/uploadsmedia/389e-2016-11-22-14-34-58.png)

**Comment by jedireza** [comment]
Thanks for creating an issue.

Since there is no `value` key in the [login route handler](https://github.com/jedireza/frame/blob/bdc3366a911039bcadc605fe809479f568bcf7f6/server/api/login.js#L20-L28), I suspect someone else is happening here.

Also you likely don't want to pass query parameters or use the "Authorization" feature with Postman, since you're trying to establish a new session when `POST`ing to `/api/login`.

**Comment by Tavousi** [comment]
ohum i get it, sorry i just new with postman.
thanks so much
