### ISSUE TITLE
Couchdb instead of mongodb for storage

### ISSUE THREAD

**Issue by mfoitzik** [jedireza/frame#169]
Hello. I was wondering if you know if anyone has forked this project to use Couchdb instead of Mongodb as the data store or if you think that there is any reason that is not practical.

**Comment by jedireza** [comment]
> I was wondering if you know if anyone has forked this project to use Couchdb instead of Mongodb

Nope.

> or if you think that there is any reason that is not practical

If you can rework the model logic and keep the same API, you'd be golden. I have my doubts about the practicality of this work though since we're depending on [`mongo-models`](https://github.com/jedireza/mongo-models), which itself depends on the MongoDB node drivers.

Otherwise you'll be making changes to just about everything.

Keep in mind, I haven't worked with CouchDB myself.
