### ISSUE TITLE
Connecting the frame to a frontend that will be rendered with jade

### ISSUE THREAD

**Issue by antzshrek** [jedireza/frame#181]
I must comment your very great effort for this great project of yours, but I have some little issues.
I have created all my jade files (all in Views) with their styling and others (in the Public), but I'm still trying to figure exactly how the entire frame routing and linking works.

I have checked various platforms to see if I could get a tutorial that might help, but can't find any.

Help please

**Comment by jedireza** [comment]
> I have created all my jade files (all in Views) with their styling and others (in the Public), but I'm still trying to figure exactly how the entire frame routing and linking works.

It sounds like you already have an app started. Typically I'd recommend starting an app with Frame or [Aqua](https://github.com/jedireza/aqua), rather than trying to integrate it into an existing app.

Aqua started out as Frame and made a handful of changes to the server side and added a front-end to it. Maybe that'll serve as a good reference.
