### ISSUE TITLE
Switch framework default authentication to cookies/sessions instead of basic auth

### ISSUE THREAD

**Issue by fishmongr** [jedireza/frame#223]
This is a killer Dev / User Portal framework boilerplate which is supposed to save folks time and automatically implement best practices. There aren't any production dev portals that use basic auth that i'm aware of, they all use cookie/sessions so I still think it would be a smart move to switch to that authentication by default, considering the Aqua version of this framework already defaults to it as well. 

As a new developer on the framework the first thing I would do is hit the interactive signup/login flows through swagger docs and find they don't work as expected because they aren't creating and maintaining sessions like they appear to be designed to do.

Previously, documentation was the biggest barrier to entry, now that we have some solid Swagger docs, I think it's more of these little technical hurdles when rolling out a new platform with this boilerplate. Setting up cookie/session support is an unexpected chore. Just like setting up forgot/reset password flows or even "abusive login attempt detection" would be chore but is already wonderfully handled for you. 

Thoughts? If agreeable we could just pull request Aqua's implementation which is working well for me.

**Comment by bmgdev** [comment]
Thanks!  So my stance on cookie based authentication... given we're in a new age of SPAs (Angular, Vue, React), decoupled APIs, mobile devices, IoT, and general decoupling from the front and back ends... cookie auth is now in the days of the past.  More and more services are deprecating cookie-based auth in favor of basic authentication with API tokens, JWT, and OAuth as they're stateless.  Rather than go into all the reasons one should avoid cookie-auth nowadays, Auth0 has a great read here:

https://auth0.com/blog/cookies-vs-tokens-definitive-guide/

![2018-06-06_14-47-07](https://user-images.githubusercontent.com/1637668/41066911-7fabfc50-6998-11e8-9636-b61ffe0cb9d4.png)

In my strong opinion, this repo should have started with JWT, but this isn't my project. :)  Moreover @jedireza 's stance over the year (years?) has been to keep this project as a bare-bones starter.  The reason I'm just contributing now is because this starter has helped immensely over time, so I owe you a few PRs. :)  But @jedireza, a reason for not committing moving forward is that I know you don't want to progress this in terms of features.  If you're interested in having more people contribute to this, throw out some ideas on direction and lets keep this project alive!  Especially now that you've done the work of a Hapi 17 up.

In my opinion, implementing cookie auth is like going back in time.  But you know how opinions go nowadays.

@fishmongr happy to see you stepping up on the docs. Swagger is an amazing step in the right direction.

**Comment by bmgdev** [comment]
Adding to the wiki has generally been your stance, I for one am good with that and think its the best approach. You know how us devs are though, we'd rather be writing code than wiki entries.  

I'll get a post up for hapi-auth-jwt2

**Comment by fishmongr** [comment]
Thanks, good feedback @bmgdev and @jedireza! 

I think updating Wiki guides on implementation scenarios would certainly be helpful. One left field solution would be for this to be including in the on-boarding that occurs with first-time-setup.js which could ask the developer which authentication method they want and to configure that automatically at setup, that'd be interesting. 

Re: Updating the swagger docs, it was a good way for me to get my head around the project, happy to continue to contribute where I can. Hapi-Swagger definitely has it's limitations still being on Swagger 2 but even Swagger 3 / OpenAPI Spec 3.0's Swagger UI is still lacking in some design and usability features for full-scale docs but it certainly can be indispensable for projects like this.

Lately I've been focused on replacing Swagger UI in my personal projects with ReDoc which is still completely powered by Swagger.json but replaces that dated limited accordion view with the now industry ubiquitous 3 panel API reference layout. https://github.com/Rebilly/ReDoc 
Docker's API is actually using it: https://docs.docker.com/engine/api/v1.25/# 

Outside of being a documentation boner it provides markdown format to add all the typical sections of content you might want to include in documentation though Github Wiki is certainly a more standard approach.

**Comment by jedireza** [comment]
> ... we'd rather be writing code than wiki entries.

Let's make sure to put some code snippets in the wiki entries 😅

> I'll get a post up for hapi-auth-jwt2

Rad! 🙏

**Comment by jedireza** [comment]
> One left field solution would be for this to be including in the on-boarding that occurs with first-time-setup.js which could ask the developer which authentication method they want and to configure that automatically at setup, that'd be interesting.

True, it would be a nice convenience. I'm just not interested in adding that kind of maintenance overhead. The templates would need to live somewhere, then we'd need to have logic to modify code files based on their choice, oh and don't forget doing this for tests too. 😬

And then we'd need to figure out how to get the live demo to run without doing some kind of environment detection and custom build or something.

Personally, that's doesn't sound like a good return on the time investment.

- - - -

Thanks again to everyone who's interested in these projects and big thanks to everyone for getting involved and contributing. ❤️

- - - -

@fishmongr I'm not sure what you meant by "Outside of being a documentation ______". I edited your comment and I'm not interested in that language. If I'm mistaken or if was a typo, that's cool, but let's just leave it at that for now.
