### ISSUE TITLE
logging

### ISSUE THREAD

**Issue by k-sheth** [jedireza/frame#34]
hapi uses good. would be good to have default file and console loggers as part of the build.

thanks

**Comment by jedireza** [comment]
It should be relatively easy to add the `good` plugin and configuration to the manifest as needed. I don't think this needs to be part of frame by default though.

Would you be willing to demonstrate what you think should be done so I get a better idea of your end goal?

**Comment by k-sheth** [comment]
The end goal would be that one can take a snapshot of this project and get started with writing their business logic without having to worry about how user management, auth or logging for that matter is implemented.

A fairly obvious default plugin entry for good might be like - 

    'good': {
        opsInterval: 1000 * 60 * 15,
        reporters: [{
            reporter: require('good-console'),
            args: [Config.get('logConfig', '/log'), {format: 'YYYY.MM.DD.HH.mm.ss.SSS'}]
        }, {
            reporter: require('good-file'),
            args: [{path: Config.get('logDir', '/log'), format: 'YYYY_MM_DD', prefix: Config.get('projectName', '/') + '_', rotate: 'daily'},
                Config.get('logConfig', '/log')]
        }],
        logRequestHeaders: true,
        logRequestPayload: true,
        logResponsePayload: true
    },

I seriously doubt any project can get off the ground without using logging and so it makes logical sense to add in frame. I am ok if you think otherwise, but I believe it would be useful to most.

One can always go and override manifest if needed.

**Comment by jedireza** [comment]
Thanks for the added detail, that helps paint a clearer picture. I agree that logs can be important. But I don't agree that logging would prevent a project form "taking off". :smiley:

The `good` config you defined probably works for your current use cases and hosting environment. I couldn't use this same config on Heroku though (for the live demo) since you don't get a blank check for writing to disk.

That's just one counter example though. Writing to disk is one of those important resources that is usually decided per project (or environment). My goal is to keep the project generic enough so these kinds of assumptions are left to the consumer, yet rich enough to be a useful boilerplate.

This might be better to add as a wiki article. Would you be willing to collect these thoughts and create a tutorial fashioned article about using `good` with Frame?
