### ISSUE TITLE
Problems with permissions and groups for Admins

### ISSUE THREAD

**Issue by Silom** [jedireza/frame#69]
Hey,
I'm about to add permissions and groups to ngFrame, but there is one problem.

In Drywall, according to the schemas you have an Array of groups and permissions.
In Frame you can push whatever to permissions and the groups are not an array after all.
I also don't see a way to update/delete permissions.

So what I actually want:

``/admins/{id}/permissions``:

A way to delete and update (update for permit true/false).
A solid schema, so I cant override the permission array and add any attributes.

``/admins/{id}/groups``:

Should be an array, is an object and can also be overridden (this could be anything ``groups: Joi.object().required()``).

If you got any questions ask me any time :)

**Comment by jedireza** [comment]
Yeah the models are a bit different in Frame than in Drywall. Essentially we just want an object where the keys are the permissions and the values are booleans (`true` if permitted and `false` otherwise).

```js
{
    MAY_LAUGH: true,
    MAY_TELL_JOKES: false
}
```

If you haven't checked out [Aqua](https://github.com/jedireza/aqua), please do. It started as Frame and is implemented with React and Flux.

Don't let Frame get in your way. Feel free to change it to best suit your needs.
