### ISSUE TITLE
config.js best practice

### ISSUE THREAD

**Issue by callerc1** [jedireza/frame#71]
Hi,

I was just wandering what would be best practice with regards to git committing the `config.js` obviously it holds some sensitive data but not quite sure how this would fit into using a CI tool with automated deploys.

**Comment by jedireza** [comment]
Thanks for opening an issue. This really depends on how the environments are setup.

With automated deploys I've typically seen apps depend on environment variables. This way your `config.js` file just references those and can be committed to the repo without worry since it doesn't actually contain secrets.

I hope that helps.

**Comment by callerc1** [comment]
@jedireza  Thanks that really helps.
