### ISSUE TITLE
logout doesn't work

### ISSUE THREAD

**Issue by x37v** [jedireza/frame#82]
I branched from master [2cf0d232b78ac011473b6c2b1ac63b91442f236a] and logout doesn't work.  I see that the logout code looks for 'username' in sessions but the key, i believe, should be 'userId' and the value shouldn't be the username it should be userId: user._id.toString()

Whats with the session being created on signup with the userId set to the username?

**Comment by jedireza** [comment]
Thanks for opening an issue. Yup, this is an artifact from using the `user.username` instead of the `user._id` for session look-ups.

And it looks like this was fixed in [Aqua](https://github.com/jedireza/aqua/):
https://github.com/jedireza/aqua/blob/master/server/api/signup.js#L161

Would you like to create a PR and submit the fix?

**Comment by x37v** [comment]
Will do [after the holiday].
