### ISSUE TITLE
Getting "Activate the plot device!" on http://localhost:8000/

### ISSUE THREAD

**Issue by bigbassroller** [jedireza/frame#96]
Hello Jedireza,

As always, thank you very much for your open source projects. They are truly awesome.

I am trying to get started with Frame, but I am running into this issue:

After doing 
```bash
$ npm run setup
```

and go to http://localhost:8000/ all I see is "Activate the plot device!"

```bash
My command line reads:
8 Jul 21:12:45 - [nodemon] v1.3.7
8 Jul 21:12:45 - [nodemon] to restart at any time, enter `rs`
8 Jul 21:12:45 - [nodemon] watching: *.*
8 Jul 21:12:45 - [nodemon] starting `node server`
Started the plot device on port 8000
```

npm version:

```bash
{ frame: '3.4.1',
  npm: '2.5.1',
  http_parser: '2.3',
  modules: '14',
  node: '0.12.0',
  openssl: '1.0.1l',
  uv: '1.0.2',
  v8: '3.28.73',
  zlib: '1.2.8' }
```

Any ideas what I am missing?

Cheers,
Mike

**Comment by jedireza** [comment]
> As always, thank you very much for your open source projects. They are truly awesome.

:pray: Thanks for opening an issue.

> Any ideas what I am missing?

You're not missing anything. Since Frame is just an API, it doesn't come with a front-end experience. You're seeing the output of the one route that renders HTML.

If you navigate to http://localhost:8000/docs you'll see the [`lout`](https://github.com/hapijs/lout) output just like the live demo.

[Aqua](https://github.com/jedireza/aqua/) on the other hand was built on top of Frame and comes with a front-end experience.

I hope this helps.

**Comment by bigbassroller** [comment]
OK cool. Yes this helps. I was thinking it was something like that.

I like the idea of Frame because I have my own ideas how I want the frontend to be;)

Thanks again,
Mike

**Comment by jedireza** [comment]
:sunglasses:
